name: presley
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch=2.1.2=py3.10_cuda12.1_cudnn8.9.2_0
  - torchvision=0.16.2=py310_cu121
  - torchaudio=2.1.2=py310_cu121
  - pytorch-cuda=12.1
  - pip:
      - -e .
