experiments:
# hash: 6634375dcfb235fb
- component: baselines
  video: dog
  width: 640
  height: 360
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 50
  target_bitrate: 0
# hash: dc391e81cdd99801
- alpha: 0.5
  beta: 0.5
  block_size: 16
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 50
  component: elvis
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  inpainter: propainter
  inpainter_params: {}
  removal_mode: blackout
  shrink_amount: 0.25
  target_bitrate: 0
  video: dog
# hash: 11aea64ab0c7a272
- alpha: 0.5
  beta: 0.5
  block_size: 16
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 50
  component: elvis
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  inpainter: propainter
  inpainter_params: {}
  removal_mode: freeze
  shrink_amount: 0.25
  target_bitrate: 0
  video: dog
# hash: cb2a0848a1c5d492
- component: baselines
  video: dog
  width: 640
  height: 360
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 55
  target_bitrate: 0
# hash: f7d79cc699093c80
- alpha: 0.5
  beta: 0.5
  block_size: 16
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 55
  component: elvis
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  inpainter: propainter
  inpainter_params: {}
  removal_mode: blackout
  shrink_amount: 0.25
  target_bitrate: 0
  video: dog
# hash: fd5665faf4106609
- alpha: 0.5
  beta: 0.5
  block_size: 16
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 55
  component: elvis
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  inpainter: propainter
  inpainter_params: {}
  removal_mode: freeze
  shrink_amount: 0.25
  target_bitrate: 0
  video: dog
# hash: 458d0c7f9a2ee6dd
- component: baselines
  video: dog
  width: 640
  height: 360
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 60
  target_bitrate: 0
# hash: cd4c80b52532af82
- alpha: 0.5
  beta: 0.5
  block_size: 16
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 60
  component: elvis
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  inpainter: propainter
  inpainter_params: {}
  removal_mode: blackout
  shrink_amount: 0.25
  target_bitrate: 0
  video: dog
# hash: e47c7af5ee5810ab
- alpha: 0.5
  beta: 0.5
  block_size: 16
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 60
  component: elvis
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  inpainter: propainter
  inpainter_params: {}
  removal_mode: freeze
  shrink_amount: 0.25
  target_bitrate: 0
  video: dog
# hash: c272f2367af21fe7
- component: baselines
  video: dog
  width: 640
  height: 360
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 63
  target_bitrate: 0
# hash: 960daa07740e3009
- alpha: 0.5
  beta: 0.5
  block_size: 16
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 63
  component: elvis
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  inpainter: propainter
  inpainter_params: {}
  removal_mode: blackout
  shrink_amount: 0.25
  target_bitrate: 0
  video: dog
# hash: b750d043f992365f
- alpha: 0.5
  beta: 0.5
  block_size: 16
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 63
  component: elvis
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  inpainter: propainter
  inpainter_params: {}
  removal_mode: freeze
  shrink_amount: 0.25
  target_bitrate: 0
  video: dog
# hash: 1e45e39ca20e50d5
- component: baselines
  video: pigs
  width: 640
  height: 360
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 50
  target_bitrate: 0
# hash: 4b0536b9b7354339
- alpha: 0.5
  beta: 0.5
  block_size: 16
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 50
  component: elvis
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  inpainter: propainter
  inpainter_params: {}
  removal_mode: blackout
  shrink_amount: 0.25
  target_bitrate: 0
  video: pigs
# hash: d8751b3614e84674
- alpha: 0.5
  beta: 0.5
  block_size: 16
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 50
  component: elvis
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  inpainter: propainter
  inpainter_params: {}
  removal_mode: freeze
  shrink_amount: 0.25
  target_bitrate: 0
  video: pigs
# hash: 711c80c110a5d359
- component: baselines
  video: pigs
  width: 640
  height: 360
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 55
  target_bitrate: 0
# hash: c7b763b41b955bd6
- alpha: 0.5
  beta: 0.5
  block_size: 16
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 55
  component: elvis
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  inpainter: propainter
  inpainter_params: {}
  removal_mode: blackout
  shrink_amount: 0.25
  target_bitrate: 0
  video: pigs
# hash: 3ec2131375bd4656
- alpha: 0.5
  beta: 0.5
  block_size: 16
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 55
  component: elvis
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  inpainter: propainter
  inpainter_params: {}
  removal_mode: freeze
  shrink_amount: 0.25
  target_bitrate: 0
  video: pigs
# hash: db046614258cedb0
- component: baselines
  video: pigs
  width: 640
  height: 360
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 60
  target_bitrate: 0
# hash: 9b69de304adba162
- alpha: 0.5
  beta: 0.5
  block_size: 16
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 60
  component: elvis
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  inpainter: propainter
  inpainter_params: {}
  removal_mode: blackout
  shrink_amount: 0.25
  target_bitrate: 0
  video: pigs
# hash: 7e00621ac44ff7ce
- alpha: 0.5
  beta: 0.5
  block_size: 16
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 60
  component: elvis
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  inpainter: propainter
  inpainter_params: {}
  removal_mode: freeze
  shrink_amount: 0.25
  target_bitrate: 0
  video: pigs
# hash: 0ae8f213b5a8da3a
- component: baselines
  video: pigs
  width: 640
  height: 360
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 63
  target_bitrate: 0
# hash: 25574cbb687a4cb5
- alpha: 0.5
  beta: 0.5
  block_size: 16
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 63
  component: elvis
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  inpainter: propainter
  inpainter_params: {}
  removal_mode: blackout
  shrink_amount: 0.25
  target_bitrate: 0
  video: pigs
# hash: 70fbca153d703b19
- alpha: 0.5
  beta: 0.5
  block_size: 16
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 63
  component: elvis
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  inpainter: propainter
  inpainter_params: {}
  removal_mode: freeze
  shrink_amount: 0.25
  target_bitrate: 0
  video: pigs
