experiments:
# hash: 01a0415053552ca0
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 50
  component: elvis
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  inpainter: none
  inpainter_params: {}
  removal_mode: blackout
  shrink_amount: 0.25
  target_bitrate: 0
  video: dog
# hash: 76c183f9001285e3
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 50
  component: elvis
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  inpainter: telea
  inpainter_params: {}
  removal_mode: blackout
  shrink_amount: 0.25
  target_bitrate: 0
  video: dog
# hash: 1fdf2a679bed0ee9
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 50
  component: elvis
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  inpainter: e2fgvi
  inpainter_params: {}
  removal_mode: blackout
  shrink_amount: 0.25
  target_bitrate: 0
  video: dog
# hash: 980693fb02d23d66
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 50
  component: elvis
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  inpainter: propainter
  inpainter_params: {}
  removal_mode: blackout
  shrink_amount: 0.25
  target_bitrate: 0
  video: dog
# hash: 483d807a34414148
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 50
  component: elvis
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  inpainter: none
  inpainter_params: {}
  removal_mode: blackout
  shrink_amount: 0.25
  target_bitrate: 0
  video: pigs
# hash: 2f6ae9a46b9f800b
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 50
  component: elvis
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  inpainter: telea
  inpainter_params: {}
  removal_mode: blackout
  shrink_amount: 0.25
  target_bitrate: 0
  video: pigs
# hash: 0e3a1f96995d513e
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 50
  component: elvis
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  inpainter: e2fgvi
  inpainter_params: {}
  removal_mode: blackout
  shrink_amount: 0.25
  target_bitrate: 0
  video: pigs
# hash: c6bd9035421f97d2
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 50
  component: elvis
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  inpainter: propainter
  inpainter_params: {}
  removal_mode: blackout
  shrink_amount: 0.25
  target_bitrate: 0
  video: pigs
# hash: 7ac7c19b436f7688
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 58
  component: elvis
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  inpainter: none
  inpainter_params: {}
  removal_mode: blackout
  shrink_amount: 0.25
  target_bitrate: 0
  video: bear
# hash: b0f8ec4cbbb84115
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 58
  component: elvis
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  inpainter: telea
  inpainter_params: {}
  removal_mode: blackout
  shrink_amount: 0.25
  target_bitrate: 0
  video: bear
# hash: 0927ac209946712b
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 58
  component: elvis
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  inpainter: e2fgvi
  inpainter_params: {}
  removal_mode: blackout
  shrink_amount: 0.25
  target_bitrate: 0
  video: bear
# hash: ccdc030699eade7c
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 58
  component: elvis
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  inpainter: propainter
  inpainter_params: {}
  removal_mode: blackout
  shrink_amount: 0.25
  target_bitrate: 0
  video: bear
# hash: 5e14b23355db2f4b
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 58
  component: elvis
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  inpainter: none
  inpainter_params: {}
  removal_mode: blackout
  shrink_amount: 0.25
  target_bitrate: 0
  video: camel
# hash: bb8119c2c965c690
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 58
  component: elvis
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  inpainter: telea
  inpainter_params: {}
  removal_mode: blackout
  shrink_amount: 0.25
  target_bitrate: 0
  video: camel
# hash: fa5c755ca0ccb3cb
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 58
  component: elvis
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  inpainter: e2fgvi
  inpainter_params: {}
  removal_mode: blackout
  shrink_amount: 0.25
  target_bitrate: 0
  video: camel
# hash: cf965f7ef594be8e
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 58
  component: elvis
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  inpainter: propainter
  inpainter_params: {}
  removal_mode: blackout
  shrink_amount: 0.25
  target_bitrate: 0
  video: camel
