experiments:
# hash: c500f8d313a17c9b
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 50
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: dog
  degradation: freeze
  restorer: none
  restorer_params: {}
# hash: 74d4c24864090da9
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 50
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: dog
  degradation: freeze
  restorer: telea
  restorer_params: {}
# hash: b1b567eec901b782
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 50
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: dog
  degradation: freeze
  restorer: e2fgvi
  restorer_params: {}
# hash: a2659081027086ba
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 50
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: dog
  degradation: freeze
  restorer: propainter
  restorer_params: {}
# hash: 651cd36f662f47f1
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 50
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: dog
  degradation: blackout
  restorer: none
  restorer_params: {}
# hash: 6bf0b5a6c51b3115
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 50
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: dog
  degradation: blackout
  restorer: telea
  restorer_params: {}
# hash: 85a3a92cd58a750a
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 50
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: dog
  degradation: blackout
  restorer: e2fgvi
  restorer_params: {}
# hash: 9083b599a6736e8d
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 50
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: dog
  degradation: blackout
  restorer: propainter
  restorer_params: {}
# hash: 2aa6947446f1c842
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 50
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: pigs
  degradation: freeze
  restorer: none
  restorer_params: {}
# hash: b99c2f7830984b1b
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 50
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: pigs
  degradation: freeze
  restorer: telea
  restorer_params: {}
# hash: c77a7899030cf1df
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 50
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: pigs
  degradation: freeze
  restorer: e2fgvi
  restorer_params: {}
# hash: bd4ba3aeb3aad546
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 50
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: pigs
  degradation: freeze
  restorer: propainter
  restorer_params: {}
# hash: ce47c5f24f56b92a
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 50
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: pigs
  degradation: blackout
  restorer: none
  restorer_params: {}
# hash: ff4800630b005b22
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 50
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: pigs
  degradation: blackout
  restorer: telea
  restorer_params: {}
# hash: 568427599a72dfa7
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 50
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: pigs
  degradation: blackout
  restorer: e2fgvi
  restorer_params: {}
# hash: e5f4d9b0a75d9ee9
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 50
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: pigs
  degradation: blackout
  restorer: propainter
  restorer_params: {}
# hash: b683ca48b74eec47
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 58
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: bear
  degradation: freeze
  restorer: none
  restorer_params: {}
# hash: 3128232321b55d45
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 58
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: bear
  degradation: freeze
  restorer: telea
  restorer_params: {}
# hash: ea178b950bb121ef
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 58
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: bear
  degradation: freeze
  restorer: e2fgvi
  restorer_params: {}
# hash: 3f02ae4404c124f4
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 58
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: bear
  degradation: freeze
  restorer: propainter
  restorer_params: {}
# hash: 81b63969ec2143c1
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 58
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: bear
  degradation: blackout
  restorer: none
  restorer_params: {}
# hash: 9ba1822671e2ab24
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 58
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: bear
  degradation: blackout
  restorer: telea
  restorer_params: {}
# hash: 8c767950d017bd90
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 58
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: bear
  degradation: blackout
  restorer: e2fgvi
  restorer_params: {}
# hash: 4e0a9032a4bd458b
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 58
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: bear
  degradation: blackout
  restorer: propainter
  restorer_params: {}
# hash: 6e879687a8759643
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 58
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: camel
  degradation: freeze
  restorer: none
  restorer_params: {}
# hash: 95217e5e3a74701a
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 58
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: camel
  degradation: freeze
  restorer: telea
  restorer_params: {}
# hash: 82430799727579fd
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 58
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: camel
  degradation: freeze
  restorer: e2fgvi
  restorer_params: {}
# hash: 5ff0bf38a226e7c8
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 58
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: camel
  degradation: freeze
  restorer: propainter
  restorer_params: {}
# hash: 3ab6bf7e33eb9b97
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 58
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: camel
  degradation: blackout
  restorer: none
  restorer_params: {}
# hash: d99ecaf6ff064139
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 58
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: camel
  degradation: blackout
  restorer: telea
  restorer_params: {}
# hash: 54cf176482676c84
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 58
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: camel
  degradation: blackout
  restorer: e2fgvi
  restorer_params: {}
# hash: 913c787e9e051793
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 58
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: camel
  degradation: blackout
  restorer: propainter
  restorer_params: {}
