experiments:
# hash: 807e09af4e5d0c6e
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 50
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: dog
  degradation: downsample
  restorer: none
  restorer_params: {}
# hash: 36d973b3d6662b9b
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 50
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: dog
  degradation: downsample
  restorer: realesrgan
  restorer_params:
    denoise_strength: 1.0
    tile: 400
# hash: ca38ca2b821af41c
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 50
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: dog
  degradation: blur
  restorer: none
  restorer_params: {}
# hash: 4cbfee60a8853cf2
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 50
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: dog
  degradation: blur
  restorer: unsharp
  restorer_params: {}
# hash: 4c20beac5c69af0b
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 55
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: dog
  degradation: downsample
  restorer: none
  restorer_params: {}
# hash: 8000cec54bd37459
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 55
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: dog
  degradation: downsample
  restorer: realesrgan
  restorer_params:
    denoise_strength: 1.0
    tile: 400
# hash: fbe8adad37b715e2
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 55
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: dog
  degradation: blur
  restorer: none
  restorer_params: {}
# hash: a4e94dd1f4c9e62c
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 55
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: dog
  degradation: blur
  restorer: unsharp
  restorer_params: {}
# hash: 617bc5747387a921
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 60
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: dog
  degradation: downsample
  restorer: none
  restorer_params: {}
# hash: 4e0bbea43ba158dc
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 60
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: dog
  degradation: downsample
  restorer: realesrgan
  restorer_params:
    denoise_strength: 1.0
    tile: 400
# hash: 1e8f71602abf30d2
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 60
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: dog
  degradation: blur
  restorer: none
  restorer_params: {}
# hash: 4c2d30801604b72d
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 60
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: dog
  degradation: blur
  restorer: unsharp
  restorer_params: {}
# hash: f67f2a531895ee8d
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 63
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: dog
  degradation: downsample
  restorer: none
  restorer_params: {}
# hash: ebccd1f79f0927de
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 63
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: dog
  degradation: downsample
  restorer: realesrgan
  restorer_params:
    denoise_strength: 1.0
    tile: 400
# hash: a5d3f8d217adbd3d
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 63
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: dog
  degradation: blur
  restorer: none
  restorer_params: {}
# hash: 0e6cd8207a2a18b6
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 63
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: dog
  degradation: blur
  restorer: unsharp
  restorer_params: {}
# hash: 043f79f6fc30be0e
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 50
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: pigs
  degradation: downsample
  restorer: none
  restorer_params: {}
# hash: 9cdf895adbad37bd
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 50
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: pigs
  degradation: downsample
  restorer: realesrgan
  restorer_params:
    denoise_strength: 1.0
    tile: 400
# hash: 3abf2419b1dcb4ad
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 50
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: pigs
  degradation: blur
  restorer: none
  restorer_params: {}
# hash: 2df2f7441fd86bd0
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 50
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: pigs
  degradation: blur
  restorer: unsharp
  restorer_params: {}
# hash: e8c528816abf1c47
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 55
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: pigs
  degradation: downsample
  restorer: none
  restorer_params: {}
# hash: 66d6041e4d7844e6
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 55
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: pigs
  degradation: downsample
  restorer: realesrgan
  restorer_params:
    denoise_strength: 1.0
    tile: 400
# hash: d7e98276aff50ac9
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 55
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: pigs
  degradation: blur
  restorer: none
  restorer_params: {}
# hash: 35451e289f7021d5
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 55
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: pigs
  degradation: blur
  restorer: unsharp
  restorer_params: {}
# hash: 02b26e19d0f2d4d7
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 60
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: pigs
  degradation: downsample
  restorer: none
  restorer_params: {}
# hash: 5c5001ebb55b92ad
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 60
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: pigs
  degradation: downsample
  restorer: realesrgan
  restorer_params:
    denoise_strength: 1.0
    tile: 400
# hash: eebb2032ca0aae46
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 60
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: pigs
  degradation: blur
  restorer: none
  restorer_params: {}
# hash: 7dcdbbbf8a668268
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 60
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: pigs
  degradation: blur
  restorer: unsharp
  restorer_params: {}
# hash: 246045841af43528
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 63
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: pigs
  degradation: downsample
  restorer: none
  restorer_params: {}
# hash: 02342c48176fe93b
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 63
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: pigs
  degradation: downsample
  restorer: realesrgan
  restorer_params:
    denoise_strength: 1.0
    tile: 400
# hash: 5d095b6a5fdabe69
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 63
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: pigs
  degradation: blur
  restorer: none
  restorer_params: {}
# hash: 5f5fabf54767dc52
- alpha: 0.5
  beta: 0.5
  block_size: 8
  codec: svtav1
  codec_params:
    preset: '8'
    qp: 63
  component: presley_ai
  composite_output: true
  fg_protect: true
  height: 360
  width: 640
  shrink_amount: 0.25
  target_bitrate: 0
  video: pigs
  degradation: blur
  restorer: unsharp
  restorer_params: {}
